language: cpp
compiler:
  - clang
  - gcc
script:
  - if [[ $CXX = clang++ ]]; then
        qmake -spec linux-clang;
    else
        qmake;
    fi
  - make check
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y qtbase5-dev qt5-default
sudo: required
dist: xenial
